# Standards: 0.11
---

# 4.1.11 Ensure unsuccessful unauthorized file access attempts are collected (Scored)

- name: 4.1.11 Ensure unsuccessful unauthorized file access attempts are collected (Scored)
  shell: "grep access {{ cis_audit_rules_filename }}"
  register: access
  changed_when: False
  ignore_errors: true
  tags:
    - "4.1.11"
    - level-2
    - section-4
    - scored


- name: 4.1.11 Ensure unsuccessful unauthorized file access attempts are collected(Verify registered output matches)
  lineinfile:
    dest: "{{ cis_audit_rules_filename }}"
    line: "{{ item }}"
  tags:
    - "4.1.11"
    - level-2
    - section-4
    - scored
