# Standards: 0.11
---

# 4.1.18 Ensure the audit configuration is immutable (Scored)

- name: 4.1.18 Ensure the audit configuration is immutable (Scored)
  shell: "grep access {{ cis_audit_rules_filename }}"
  register: access
  changed_when: False
  ignore_errors: true
  tags:
    - "4.1.18"
    - level-2
    - section-4
    - scored


- name: 4.1.18 Ensure the audit configuration is immutable (Scored)
  lineinfile:
    dest: "{{ cis_audit_rules_filename }}"
    line: "{{ item }}"
  with_items:
    - '# 4.1.18 Ensure the audit configuration is immutable'
    - '-e 2'

  tags:
    - "4.1.18"
    - level-2
    - section-4
    - scored
