# Standards: 0.11
---

# 3.1.2 Ensure packet redirect sending is disabled

- name: 3.1.2 - Ensure packet redirect sending is disabled
  sysctl:
    name: net.ipv4.conf.all.send_redirects
    value: 0
    state: present
  tags:
    - level-1
    - section-3
    - "3.1.2"
    - scored

- name: 3.1.2 - Ensure packet redirect sending is disabled
  sysctl:
    name: net.ipv4.conf.default.send_redirects
    value: 0
    state: present
  tags:
    - level-1
    - section-3
    - "3.1.2"
    - scored

- name: 3.1.2 - Ensure packet redirect sending is disabled in active kernel parameters
  command: "{{ item }}"
  with_items:
    - "sysctl -w net.ipv4.conf.all.send_redirects=0"
    - "sysctl -w net.ipv4.conf.default.send_redirects=0"
    - "sysctl -w net.ipv4.route.flush=1"
  tags:
    - level-1
    - section-3
    - "3.1.2"
    - scored
