# Standards: 0.11
---

# 3.5.2.1 Ensure IPv6 default deny firewall policy 

- name: 3.5.2.1 - Ensure default deny firewall policy(DROP INPUT)
  command: "{{ item }}"
  with_items:
    - "ip6tables -P INPUT DROP"
    - "ip6tables -P OUTPUT DROP"
    - "ip6tables -P FORWARD DROP"
  tags:
    - level-1
    - section-3
    - "3.5.2.1"
    - scored
